name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}} # Update if needed

    - name: Deploy via AWS SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploying new code to dadjokes server" \
          --targets "Key=tag:Name1,Values=my-ec2-server" \
          --parameters commands=["cd ~/dadjokes", "git pull", "npm install", "pm2 restart dadjokes || pm2 start server.js --name dadjokes"] \
          --timeout-seconds 600 \
          --region ${{ secrets.AWS_REGION }} \
          --output text
